### ISSUE TITLE
Load Blade View ?

### ISSUE THREAD

**Issue by mansouralex** [maxxscho/laravel-tcpdf#17]
Is there a way to load view and passing data to the view?

thanks.

**Comment by maxxscho** [comment]
I don't know what you mean. Please describe your problem more detailed, maybe with a code sample.

**Comment by mansouralex** [comment]
What I'm looking for is to generate PDF from Blade View, for example 

$pdf = PDF::loadView('pdf.invoice', $data);

**Comment by maxxscho** [comment]
That's not possible with TCPDF.

You need something like [HTML2PDF](http://html2pdf.fr/de/default) or [DomPDF](https://github.com/dompdf/dompdf).

**Comment by mansouralex** [comment]
Thank you for your suggestions, I have tried DomPDF but the problem it doesn't render arabic letters correctly. I have tried all possible solutions with no luck.

**Comment by maxxscho** [comment]
Hmmm… und you can't generate the PDF "manually"?

**Comment by mansouralex** [comment]
what do you mean by manually ?

**Comment by maxxscho** [comment]
Like in [this little example](https://github.com/maxxscho/laravel-tcpdf#installation) in the readme.

**Comment by mansouralex** [comment]
you mean by using this : PDF::Write(0, 'Hello World');

actually the PDF documents that I need to generate contains data displayed in table, could you give me example how I can do it using PDF::Write(); function?

**Comment by maxxscho** [comment]
My Package is "only" a service wrapper for TCPDF. This means you can use all TCPDF functions - see the [docs](http://www.tcpdf.org/doc/code/classTCPDF.html).
Here are some [examples](http://www.tcpdf.org/examples.php) including tables like [this code](http://www.tcpdf.org/examples/example_048.phps) for [this PDF](http://www.tcpdf.org/examples/example_048.pdf).

I hope this helps.

**Comment by mansouralex** [comment]
I will try it. 
Thank you.

**Comment by maxxscho** [comment]
You're welcome.
